### ISSUE TITLE
How the heck do you even install it?

### ISSUE THREAD

**Issue by gdandsm64fan123** [JHRobotics/vmdisp9x#9]
listen man, i aint no nerd so i dont know shit about installing drivers. Im using VirtualBox 7.4 which should be compatible, can anyone give me a tutorial or smth?

**Comment by FranceBB** [comment]
Download the .ima from the release page.
The .ima is an image of a Floppy Disk where you have all the installation files.
You need to attach it to your Virtualbox VM by clicking "+" in Add Floppy Drive so that it's gonna be like this:
![image](https://github.com/user-attachments/assets/431dbe24-e556-4f56-9f5e-9e608b027868)

Then boot into Windows 98, go to My Computer
![image](https://github.com/user-attachments/assets/e447ecd8-7eb8-4555-be5a-30ff6b3429a1)

Right click, properties
![image](https://github.com/user-attachments/assets/44dc6f49-1583-4bed-a9f8-408ee25717dc)

go to Device Properties and double click on the VBox VGA PCI Adapter
![image](https://github.com/user-attachments/assets/ffb430ae-1753-40a6-87bd-e4f9cf26e898)

select "update drivers" (or install drivers in your case as it would be yellow with a ? as it hasn't been installed yet)
![image](https://github.com/user-attachments/assets/a143722e-3d0d-490e-b760-48772f61a2c8)

click next
![image](https://github.com/user-attachments/assets/33e4fbdb-aebb-430b-83eb-629bd9d5a467)

click next
![image](https://github.com/user-attachments/assets/7b5e7a78-9cf3-4988-8db7-93bdaae298d0)

select "floppy disk drives" with the tickbox
![image](https://github.com/user-attachments/assets/04a49943-5e45-4f68-82f7-89500a8dd2f0)

Windows will find the driver in the virtual floppy disk, click next once again, let it do its thing and then reboot
![image](https://github.com/user-attachments/assets/60d9aa3f-ae1b-4191-b894-30c0c80683bb)

After rebooting, you're gonna be able to the desktop, right click on properties and in the settings you're gonna see all the high resolutions, including FULL HD 1920x1080 
![image](https://github.com/user-attachments/assets/f8483642-ddf7-40ed-b664-19ef4fc1671e)


Alternatively, if you just want an exe that installs everything in one way you can use his SoftGPU package https://github.com/JHRobotics/softgpu and just use the installation wizard by running the exe and hitting next next, selecting virtualbox and clicking done. The download for that is here https://github.com/JHRobotics/softgpu/releases and you need to attach the iso file to the VM in a similar way but instead of a virtual floppy you're gonna have a virtual CD.

**Comment by FranceBB** [comment]
p.s none of us is a nerd, trust me, but we were there when Windows98 was around and we had to insert Floppy Disks, so it doesn't make much difference to insert a virtual floppy disk image instead ;)
